resolver: nightly-2021-07-04  # 9.0.1
# resolver: lts-18.1  # 8.10.4
# resolver: lts-16.31  # 8.8.4
# resolver: lts-14.27  # 8.6.5

packages:
- llvm-hs
- llvm-hs-pure

# We should not need to do this, but unfortunately, removing it breaks the stack build.
ghc-options:
  llvm-hs: -optcxx=-std=c++14 -optcxx=-lstdc++ -optcxx=-fno-rtti
